### ISSUE TITLE
Erreur à la compilation SSR

### ISSUE THREAD

**Issue by lpofredc** [PnX-SI/GeoNature-citizen#120]
L'erreur suivante est soulevée lors de la compilation en Server Side Rendering

```
WARNING in ./node_modules/jsdom/lib/jsdom/utils.js 216:21-40
Critical dependency: the request of a dependency is an expression
 @ ./node_modules/jsdom/lib/jsdom.js
 @ ./node_modules/mock-browser/lib/MockBrowser.js
 @ ./node_modules/mock-browser/index.js
 @ ./server.ts
```

**Comment by lpofredc** [comment]
Premier problème a priori résolu, mais de nouveau un pb:

```
/home/fcloitre/Dev/gncitizen/frontend/dist/server.js:279794
				__WEBPACK_AMD_DEFINE_RESULT__ !== undefined && (module.exports = __WEBPACK_AMD_DEFINE_RESULT__));else {}})(this,function(){"use strict";function b(a,b){return"undefined"==typeof b?b={autoBom:!1}:"object"!=typeof b&&(console.warn("Deprecated: Expected third argument to be a object"),b={autoBom:!b}),b.autoBom&&/^\s*(?:text\/\S*|application\/xml|\S*\/\S*\+xml)\s*;.*charset\s*=\s*utf-8/i.test(a.type)?new Blob(["\uFEFF",a],{type:a.type}):a}function c(b,c,d){var e=new XMLHttpRequest;e.open("GET",b),e.responseType="blob",e.onload=function(){a(e.response,c,d)},e.onerror=function(){console.error("could not download file")},e.send()}function d(a){var b=new XMLHttpRequest;b.open("HEAD",a,!1);try{b.send()}catch(a){}return 200<=b.status&&299>=b.status}function e(a){try{a.dispatchEvent(new MouseEvent("click"))}catch(c){var b=document.createEvent("MouseEvents");b.initMouseEvent("click",!0,!0,window,0,0,0,80,20,!1,!1,!1,!1,0,null),a.dispatchEvent(b)}}var f="ob

ReferenceError: HTMLAnchorElement is not defined
    at Object.<anonymous> (/home/fcloitre/Dev/gncitizen/frontend/dist/server.js:279794:1197)
    at L.Control.Fullscreen.L.Control.extend.options.position (/home/fcloitre/Dev/gncitizen/frontend/dist/server.js:279793:37)
    at Object.L.Control.Fullscreen.L.Control.extend.options.position (/home/fcloitre/Dev/gncitizen/frontend/dist/server.js:279794:111)
    at __webpack_require__ (/home/fcloitre/Dev/gncitizen/frontend/dist/server.js:20:30)
    at Object.file-saver (/home/fcloitre/Dev/gncitizen/frontend/dist/server.js:257206:18)
    at __webpack_require__ (/home/fcloitre/Dev/gncitizen/frontend/dist/server.js:250368:30)
    at Module../src/app/auth/user-dashboard/user-dashboard.component.ts (/home/fcloitre/Dev/gncitizen/frontend/dist/server.js:253372:68)
    at __webpack_require__ (/home/fcloitre/Dev/gncitizen/frontend/dist/server.js:250368:30)
    at Module../src/app/auth/user-dashboard/user-dashboard.component.ngfactory.js (/home/fcloitre/Dev/gncitizen/frontend/dist/server.js:253195:83)
    at __webpack_require__ (/home/fcloitre/Dev/gncitizen/frontend/dist/server.js:250368:30)

```

**Comment by lpofredc** [comment]
Toujours d'actualité. Voici ce qui est observé:
- Lors d'une compilation avec la commande `npm run build:ssr`, la compilation du front en mode server side rendering fonctionne. Mais lorsque l'on souhaite servir cette version `npm run serve:ssr`, il y a erreur car il cherche la version `fr`, définie par défaut https://github.com/PnX-SI/GeoNature-citizen/blob/2284b7657bda6db0e7c9389dd21ca8f943eb70dc/frontend/server.ts#L26-L28

```
# npm run serve:ssr

> frontend@0.0.0 serve:ssr /home/fcloitre/Dev/gncitizen/frontend
> node dist/server

fs.js:114
    throw err;
    ^

Error: ENOENT: no such file or directory, open '/home/fcloitre/Dev/gncitizen/frontend/dist/browser/fr/index.html'
    at Object.openSync (fs.js:443:3)
    at readFileSync (fs.js:343:35)
    at Module.__values (/home/fcloitre/Dev/gncitizen/frontend/dist/server.js:124:71)
    at __webpack_require__ (/home/fcloitre/Dev/gncitizen/frontend/dist/server.js:20:30)
    at /home/fcloitre/Dev/gncitizen/frontend/dist/server.js:84:18
    at Object.<anonymous> (/home/fcloitre/Dev/gncitizen/frontend/dist/server.js:87:10)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! frontend@0.0.0 serve:ssr: `node dist/server`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the frontend@0.0.0 serve:ssr script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/fcloitre/.npm/_logs/2019-11-27T23_30_13_351Z-debug.log
```

- Lors d'une compilation avec la commande `npm run build:i18n-ssr`, la compilation échoue avec la sortie suivante (plus obscure...)



```
# npm run build:i18n-ssr

> frontend@0.0.0 build:i18n-ssr /home/fcloitre/Dev/gncitizen/frontend
> npm run build:client-and-server-bundles-i18n && npm run compile:server


> frontend@0.0.0 build:client-and-server-bundles-i18n /home/fcloitre/Dev/gncitizen/frontend
> ng run frontend:build:fr && ng run frontend:build:en && ng run frontend:server:production

                                                             
chunk {0} runtime.a6586930f507951256e4.js (runtime) 1.41 kB [entry] [rendered]
chunk {1} main.340a0c9b260735ed45e8.js (main) 128 bytes [initial] [rendered]
chunk {2} polyfills.e938bf2533a56ddecba2.js (polyfills) 130 bytes [initial] [rendered]
chunk {3} polyfills-es5.5f5c13eaf4188dd56cfd.js (polyfills-es5) 69.8 kB [initial] [rendered]
chunk {4} styles.8805f7afff7ed204a83b.css (styles) 191 kB [initial] [rendered]
chunk {scripts} scripts.78bc0368faf986bb465e.js (scripts) 373 kB [entry] [rendered]
Date: 2019-11-27T23:28:21.682Z - Hash: 139da3bb61b802c70c74 - Time: 7039ms

WARNING in Invalid property name 'r' at 1034:383. Ignoring.
WARNING in Invalid property name 'r' at 1034:406. Ignoring.
WARNING in Invalid property name 'r' at 1034:430. Ignoring.
WARNING in Invalid property name 'r' at 1034:493. Ignoring.
WARNING in Invalid property name 'r' at 1034:516. Ignoring.
WARNING in Invalid property name 'r' at 1034:540. Ignoring.

ERROR in Cannot read property 'start' of null
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! frontend@0.0.0 build:client-and-server-bundles-i18n: `ng run frontend:build:fr && ng run frontend:build:en && ng run frontend:server:production`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the frontend@0.0.0 build:client-and-server-bundles-i18n script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/fcloitre/.npm/_logs/2019-11-27T23_28_21_734Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! frontend@0.0.0 build:i18n-ssr: `npm run build:client-and-server-bundles-i18n && npm run compile:server`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the frontend@0.0.0 build:i18n-ssr script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/fcloitre/.npm/_logs/2019-11-27T23_28_21_749Z-debug.log
```
Et le log en question
```└─▪ tail -n 100 /home/fcloitre/.npm/_logs/2019-11-27T23_28_21_749Z-debug.log
0 info it worked if it ends with ok
1 verbose cli [ '/home/fcloitre/.nvm/versions/node/v10.16.0/bin/node',
1 verbose cli   '/home/fcloitre/.nvm/versions/node/v10.16.0/bin/npm',
1 verbose cli   'run',
1 verbose cli   'build:i18n-ssr' ]
2 info using npm@6.9.0
3 info using node@v10.16.0
4 verbose run-script [ 'prebuild:i18n-ssr', 'build:i18n-ssr', 'postbuild:i18n-ssr' ]
5 info lifecycle frontend@0.0.0~prebuild:i18n-ssr: frontend@0.0.0
6 info lifecycle frontend@0.0.0~build:i18n-ssr: frontend@0.0.0
7 verbose lifecycle frontend@0.0.0~build:i18n-ssr: unsafe-perm in lifecycle true
8 verbose lifecycle frontend@0.0.0~build:i18n-ssr: PATH: /home/fcloitre/.nvm/versions/node/v10.16.0/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/fcloitre/Dev/gncitizen/frontend/node_modules/.bin:/home/fcloitre/.pyenv/plugins/pyenv-virtual/shims:/home/fcloitre/.pyenv/shims:/home/fcloitre/.pyenv/bin:/home/fcloitre/.pyenv/plugins/pyenv-virtual/shims:/home/fcloitre/.pyenv/shims:/home/fcloitre/.pyenv/bin:/home/fcloitre/.nvm/versions/node/v10.16.0/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/opt/nginx/sbin
9 verbose lifecycle frontend@0.0.0~build:i18n-ssr: CWD: /home/fcloitre/Dev/gncitizen/frontend
10 silly lifecycle frontend@0.0.0~build:i18n-ssr: Args: [ '-c',
10 silly lifecycle   'npm run build:client-and-server-bundles-i18n && npm run compile:server' ]
11 silly lifecycle frontend@0.0.0~build:i18n-ssr: Returned: code: 1  signal: null
12 info lifecycle frontend@0.0.0~build:i18n-ssr: Failed to exec build:i18n-ssr script
13 verbose stack Error: frontend@0.0.0 build:i18n-ssr: `npm run build:client-and-server-bundles-i18n && npm run compile:server`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/home/fcloitre/.nvm/versions/node/v10.16.0/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:198:13)
13 verbose stack     at ChildProcess.<anonymous> (/home/fcloitre/.nvm/versions/node/v10.16.0/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:198:13)
13 verbose stack     at maybeClose (internal/child_process.js:982:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
14 verbose pkgid frontend@0.0.0
15 verbose cwd /home/fcloitre/Dev/gncitizen/frontend
16 verbose Linux 5.0.0-32-generic
17 verbose argv "/home/fcloitre/.nvm/versions/node/v10.16.0/bin/node" "/home/fcloitre/.nvm/versions/node/v10.16.0/bin/npm" "run" "build:i18n-ssr"
18 verbose node v10.16.0
19 verbose npm  v6.9.0
20 error code ELIFECYCLE
21 error errno 1
22 error frontend@0.0.0 build:i18n-ssr: `npm run build:client-and-server-bundles-i18n && npm run compile:server`
22 error Exit status 1
23 error Failed at the frontend@0.0.0 build:i18n-ssr script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true 

```

**Comment by patkap** [comment]
Peut-être avec le flag `--configuration=fr` ?

**Comment by lpofredc** [comment]
Merci @patkap, mais malheureusment le flag `--configuration=fr` n'a aucune incidence.

**Piste**, en déplaçant manuellement le `build` généré par la commande `npm run build:ssr` de `frontend/dist/browser` à `frontend/dist/browser/fr`, la commande `npm run serve:ssr` fonctionne  et lance le serveur sur le port 4000.  L'erreur semble venir de la config angular.json ou de `server.ts` avec un cafouillage au niveau de la gestion des compilations en locales (i18n: `fr` ou `en`). 

**Solution partielle** : La langue française étant la langue par défaut, en modifiant `angular.json` en lui ajoutant `"outputPath": "dist/browser/fr/",` dans `projects > frontend > architect > build > configurations > production`, l'erreur sur `npm run serve:ssr` est résolue, mais pas `npm run build:i18n-ssr`.

La config **nginx** suivante permet de servir cette instance fonctionnelle en "_full_" `server-side-rendering`.

```nginx
upstream gnc-ssr {
    server localhost:4000;
}

server {

    listen 80;
    index index.html ;
    server_name gnc-ssr.local;
    root /home/fcloitre/Dev/gncitizen/frontend/dist/browser/fr;

    location / {
        try_files $uri $uri @backend
    }

    location @backend{
        proxy_pass http://gnc-ssr;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $http_host;
        proxy_http_version 1.1;
        proxy_set_header X-NginX-Proxy true;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_cache_bypass $http_upgrade;
        proxy_redirect off;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
```
