### ISSUE TITLE
Copie des médias dans le /frontend/dist/browser/fr/assets/ ?

### ISSUE THREAD

**Issue by Splendens** [PnX-SI/GeoNature-citizen#423]
Bonjour,

J'ai installé une instance de GN-citizen 1.1.0 sur un serveur debian (qui contenait déjà une instance GN / TH / UH). L'installation se fait sans problème avec le script automatique. Merci pour cette version de l'appli !

Tout semble fonctionner correctement, sauf les médias ajoutés dans l'interface d'administration (/api/admin) : quand j'ajoute une image, elle se trouve bien dans le dossier /gncitizen/media/, mais pas dans le dossier du frontend. Pour avoir accès à l'image, je dois la copier manuellement dans le dossier gncitizen/frontend/dist/browser/fr/assets/.

J'ai raté un point important dans l'installation ou la config ? 

J'ai tenté de lancer un build comme précisé dans la doc (https://geonature-citizen.readthedocs.io/fr/latest/installation.html#faire-le-build-du-code-du-frontend), mais les dossiers de langue ne sont pas créés, ce qui me revoit une erreur : 

```

 Error: Failed to lookup view "fr/index" in views directory "/home/moi/gncitizen/frontend/dist/browser"
    at Function.render (/home/moi/gncitizen/frontend/dist/server.js:129932:17)
    at ServerResponse.render (/home/moi/gncitizen/frontend/dist/server.js:140366:7)
    at /home/moi/gncitizen/frontend/dist/server.js:168:9
    at Layer.handle [as handle_request] (/home/moi/gncitizen/frontend/dist/server.js:131741:5)
    at next (/home/moi/gncitizen/frontend/dist/server.js:131487:13)
    at Route.dispatch (/home/moi/gncitizen/frontend/dist/server.js:131457:3)
    at Layer.handle [as handle_request] (/home/moi/gncitizen/frontend/dist/server.js:131741:5)
    at /home/moi/gncitizen/frontend/dist/server.js:130947:15
    at param (/home/moi/gncitizen/frontend/dist/server.js:131028:14)
    at param (/home/moi/gncitizen/frontend/dist/server.js:131039:14)
```

Merci d'avance si quelqu'un a une piste !

**Comment by Splendens** [comment]
Ok, j'ai fini par trouver pour l'affichage des photos : pour afficher une image ajoutée depuis l'interface d'administration, il faut renseigner "/api/media/mon_image.jpg" dans le champ du formulaire, vu que c'est dans ce dossier que le fichier est enregistré.
